name: seo_example

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  faker: ^2.2.0
  auto_route: ^10.0.1
  visibility_detector: ^0.4.0+2
  seo:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.13
