name: seo_example

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  faker: ^2.1.0
  auto_route: ^8.0.0
  visibility_detector: ^0.4.0+2
  seo:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
